spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blog_db
    username: user_admin
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      schema-locations: classpath:init-db.sql
      mode: always
server:
  port: 8088